version: '3.3'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # Local path where your home assistant config will be stored
      - ~/homeautomation-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    user: "${LOCAL_USER}:${LOCAL_USER}"